#!/usr/bin/env python

try:
    # ------------------------------------------------------------------
    # If running the script from somewhere else, can add location of the
    # mara_tools module to maratool_cfg.py by doing
    #
    # sys.path += ['/path/containing/mara_tools']
    # ------------------------------------------------------------------
    import maratool_cfg
except ImportError:
    pass


import sys
import argparse
import numpy as np
import h5py
from mara_tools import gaussfield
from mara_tools import chkptlog
from mara_tools import synchsky
from mara_tools import genchkpt
from mara_tools import cutplanes
from mara_tools import reductions


def cmd_gaussian_bfield():
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", "--outfile",
                        help="output HDF5 file name", default="chkpt.0000.h5")
    parser.add_argument("--rms", type=float,
                        help="RMS value of magnetic field", default=1.0)
    parser.add_argument("-N", "--resolution", type=int,
                        help="domain resulution (N^3)", default=32)
    args = parser.parse_args()

    def small_scale(k):
        k0 = 0.01
        return pow(k,12) * np.exp(-k/k0);

    N = args.resolution
    chkpt = genchkpt.MaraCheckpointCreator(args.outfile, [N,N,N], mhd=True)
    field = gaussfield.GaussianRandomVectorField3d(N, rms=args.rms,
                                                   Pofk=small_scale)
    B = field.get_field(zeta=1.0)

    def callback(prim):
        prim['pre'][:] = 1.0
        prim['rho'][:] = 1.0
        prim['vx'][:] = 0.0
        prim['vy'][:] = 0.0
        prim['vz'][:] = 0.0
        prim['Bx'][:] = B[0]
        prim['By'][:] = B[1]
        prim['Bz'][:] = B[2]

    chkpt.apply_initial_data(callback)



def cmd_show_log():
    parser = argparse.ArgumentParser()
    parser.add_argument("filename")
    args = parser.parse_args()

    chkpt = chkptlog.MaraCheckpointLoggedData(args.filename)
    chkpt.plot_fields(['mag', 'kin'])



def cmd_synchsky():
    parser = argparse.ArgumentParser()
    parser.add_argument("filename")
    parser.add_argument("-o", "--outfile", type=str,
                        help="output HDF5 file name", default="synchsky.h5")
    parser.add_argument("-a", "--axis", type=int, choices=[0,1,2], default=0,
                        help="output HDF5 file name")
    parser.add_argument("--show", action="store_true")
    args = parser.parse_args()

    try:
        chkpt = synchsky.StokesMaraCheckpointFile(args.filename)
        stokes = chkpt.stokes_image(axis=args.axis)
        stokes.save(args.outfile)
        if args.show:
            stokes.make_figures2()
    except RuntimeError:
        stokes = synchsky.StokesVectorsImage()
        stokes.load(args.filename)
        stokes.make_figures2()



def cmd_cutplanes():
    cls = cutplanes.MaraCheckpointCutplaneExtractor
    parser = argparse.ArgumentParser()
    get_kwargs = cls.populate_parser('plot_slice', parser)
    parser.add_argument("filename")
    pargs = parser.parse_args()
    chkpt = cls(pargs.filename)
    chkpt.plot_slice(**get_kwargs(pargs))



def cmd_power_spectrum():
    cls = reductions.MaraReductionsReader
    parser = argparse.ArgumentParser()
    get_kwargs = cls.populate_parser('plot_power_spectra', parser)
    parser.add_argument("filename")
    pargs = parser.parse_args()
    reduc = cls(pargs.filename)
    reduc.plot_power_spectra(**get_kwargs(pargs))



if __name__ == "__main__":

    cmds = [c for c in dir() if c.startswith('cmd_')]

    if len(sys.argv) > 1 and 'cmd_' + sys.argv[1] in cmds:
        cmd = 'cmd_' + sys.argv[1]
        del sys.argv[1]
        exec(cmd + "()")
    else:
        print "commands are:"
        print "\t" + "\n\t".join([c[4:] for c in cmds])

